package com.papirus.GUI;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.util.ArrayList;

/**
 * Created by Çağatay Uslu on 23.07.2017.
 */
public class PlayPanel extends JWindow{

    Container contentPane, bottomPane;
    Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
    GridLayout grid;
    EmptyBorder emptyBorder;
    private JButton[] square = new JButton[36];

    public PlayPanel(){

        contentPane = getContentPane();
        setSize(500,500);
        setLayout(new BorderLayout());
        setLocation(dimension.width / 2 - this.getSize().width / 2, dimension.height / 2 - this.getSize().height / 2);
        setLayout(new BorderLayout());

        emptyBorder = new EmptyBorder(10,40,10,40);
        rootPane.setBorder(emptyBorder);

        grid = new GridLayout(6,6);
        bottomPane = new Container();
        bottomPane.setLayout(grid);
        contentPane.add(bottomPane, BorderLayout.SOUTH);


        final JButton button1 = new JButton();
        button1.setBackground(new Color(-14776091));
        button1.setBorderPainted(false);
        button1.setContentAreaFilled(false);
        button1.setFont(new Font(null, Font.PLAIN, 36));
        button1.setMargin(new Insets(0, 0, 0, 0));
        button1.setMaximumSize(new Dimension(70,70));
        button1.setMinimumSize(new Dimension(70,70));
        button1.setOpaque(true);
        button1.setPreferredSize(new Dimension(70,70));
        button1.setText("2");
        bottomPane.add(button1);
        final JButton button2 = new JButton();
        button2.setBackground(new Color(-291840));
        button2.setBorderPainted(false);
        button2.setContentAreaFilled(false);
        button2.setMargin(new Insets(0, 0, 0, 0));
        button2.setMaximumSize(new Dimension(30,30));
        button2.setMinimumSize(new Dimension(30,30));
        button2.setOpaque(true);
        button2.setPreferredSize(new Dimension(30,30));
        button2.setText("1");
        bottomPane.add(button2);
        final JButton button3 = new JButton();
        button3.setBackground(new Color(-1754827));
        button3.setBorderPainted(false);
        button3.setContentAreaFilled(false);
        button3.setMargin(new Insets(0, 0, 0, 0));
        button3.setMaximumSize(new Dimension(30,30));
        button3.setMinimumSize(new Dimension(30,30));
        button3.setOpaque(true);
        button3.setPreferredSize(new Dimension(30,30));
        button3.setText("1");
        bottomPane.add(button3);
        final JButton button4 = new JButton();
        button4.setBackground(new Color(-14776091));
        button4.setBorderPainted(false);
        button4.setContentAreaFilled(false);
        button4.setMargin(new Insets(0, 0, 0, 0));
        button4.setMaximumSize(new Dimension(30,30));
        button4.setMinimumSize(new Dimension(30,30));
        button4.setOpaque(true);
        button4.setPreferredSize(new Dimension(30,30));
        button4.setText("2");
        bottomPane.add(button4);
        final JButton button5 = new JButton();
        button5.setBackground(new Color(-12345273));
        button5.setBorderPainted(false);
        button5.setContentAreaFilled(false);
        button5.setMargin(new Insets(0, 0, 0, 0));
        button5.setMaximumSize(new Dimension(30,30));
        button5.setMinimumSize(new Dimension(30,30));
        button5.setOpaque(true);
        button5.setPreferredSize(new Dimension(30,30));
        button5.setText("4");
        bottomPane.add(button5);
        final JButton button6 = new JButton();
        button6.setBackground(new Color(-12345273));
        button6.setBorderPainted(false);
        button6.setContentAreaFilled(false);
        button6.setFocusable(true);
        button6.setMargin(new Insets(0, 0, 0, 0));
        button6.setMaximumSize(new Dimension(30,30));
        button6.setMinimumSize(new Dimension(30,30));
        button6.setOpaque(true);
        button6.setPreferredSize(new Dimension(30,30));
        button6.setText("4");
        bottomPane.add(button6, new GridLayout(2, 3, 1, 1));
        final JButton button7 = new JButton();
        button7.setBackground(new Color(-141259));
        button7.setBorderPainted(false);
        button7.setContentAreaFilled(false);
        button7.setMargin(new Insets(0, 0, 0, 0));
        button7.setMaximumSize(new Dimension(30,30));
        button7.setMinimumSize(new Dimension(30,30));
        button7.setOpaque(true);
        button7.setPreferredSize(new Dimension(30,30));
        button7.setText("3");
        bottomPane.add(button7);
        final JButton button8 = new JButton();
        button8.setBackground(new Color(-1754827));
        button8.setBorderPainted(false);
        button8.setContentAreaFilled(false);
        button8.setMargin(new Insets(0, 0, 0, 0));
        button8.setMaximumSize(new Dimension(30,30));
        button8.setMinimumSize(new Dimension(30,30));
        button8.setOpaque(true);
        button8.setPreferredSize(new Dimension(30,30));
        button8.setText("1");
        bottomPane.add(button8);
        final JButton button9 = new JButton();
        button9.setBackground(new Color(-1754827));
        button9.setBorderPainted(false);
        button9.setContentAreaFilled(false);
        button9.setMargin(new Insets(0, 0, 0, 0));
        button9.setMaximumSize(new Dimension(30,30));
        button9.setMinimumSize(new Dimension(30,30));
        button9.setOpaque(true);
        button9.setPreferredSize(new Dimension(30,30));
        button9.setText("1");
        bottomPane.add(button9);
        final JButton button10 = new JButton();
        button10.setBackground(new Color(-141259));
        button10.setBorderPainted(false);
        button10.setContentAreaFilled(false);
        button10.setMargin(new Insets(0, 0, 0, 0));
        button10.setMaximumSize(new Dimension(30,30));
        button10.setMinimumSize(new Dimension(30,30));
        button10.setOpaque(true);
        button10.setPreferredSize(new Dimension(30,30));
        button10.setText("3");
        bottomPane.add(button10);
        final JButton button11 = new JButton();
        button11.setBackground(new Color(-291840));
        button11.setBorderPainted(false);
        button11.setContentAreaFilled(false);
        button11.setMargin(new Insets(0, 0, 0, 0));
        button11.setMaximumSize(new Dimension(30,30));
        button11.setMinimumSize(new Dimension(30,30));
        button11.setOpaque(true);
        button11.setPreferredSize(new Dimension(30,30));
        button11.setText("5");
        bottomPane.add(button11);
        final JButton button12 = new JButton();
        button12.setBackground(new Color(-1754827));
        button12.setBorderPainted(false);
        button12.setContentAreaFilled(false);
        button12.setMargin(new Insets(0, 0, 0, 0));
        button12.setMaximumSize(new Dimension(30,30));
        button12.setMinimumSize(new Dimension(30,30));
        button12.setOpaque(true);
        button12.setPreferredSize(new Dimension(30,30));
        button12.setText("1");
        bottomPane.add(button12);
        final JButton button13 = new JButton();
        button13.setBackground(new Color(-1754827));
        button13.setBorderPainted(false);
        button13.setContentAreaFilled(false);
        button13.setMargin(new Insets(0, 0, 0, 0));
        button13.setMaximumSize(new Dimension(30,30));
        button13.setMinimumSize(new Dimension(30,30));
        button13.setOpaque(true);
        button13.setPreferredSize(new Dimension(30,30));
        button13.setText("1");
        bottomPane.add(button13);
        final JButton button14 = new JButton();
        button14.setBackground(new Color(-1754827));
        button14.setBorderPainted(false);
        button14.setContentAreaFilled(false);
        button14.setMargin(new Insets(0, 0, 0, 0));
        button14.setMaximumSize(new Dimension(30,30));
        button14.setMinimumSize(new Dimension(30,30));
        button14.setOpaque(true);
        button14.setPreferredSize(new Dimension(30,30));
        button14.setText("1");
        bottomPane.add(button14);
        final JButton button15 = new JButton();
        button15.setBackground(new Color(-291840));
        button15.setBorderPainted(false);
        button15.setContentAreaFilled(false);
        button15.setMargin(new Insets(0, 0, 0, 0));
        button15.setMaximumSize(new Dimension(30,30));
        button15.setMinimumSize(new Dimension(30,30));
        button15.setOpaque(true);
        button15.setPreferredSize(new Dimension(30,30));
        button15.setText("5");
        bottomPane.add(button15);
        final JButton button16 = new JButton();
        button16.setBackground(new Color(-14776091));
        button16.setBorderPainted(false);
        button16.setContentAreaFilled(false);
        button16.setMargin(new Insets(0, 0, 0, 0));
        button16.setMaximumSize(new Dimension(30,30));
        button16.setMinimumSize(new Dimension(30,30));
        button16.setOpaque(true);
        button16.setPreferredSize(new Dimension(30,30));
        button16.setText("2");
        bottomPane.add(button16);
        final JButton button17 = new JButton();
        button17.setBackground(new Color(-141259));
        button17.setBorderPainted(false);
        button17.setContentAreaFilled(false);
        button17.setMargin(new Insets(0, 0, 0, 0));
        button17.setMaximumSize(new Dimension(30,30));
        button17.setMinimumSize(new Dimension(30,30));
        button17.setOpaque(true);
        button17.setPreferredSize(new Dimension(30,30));
        button17.setText("3");
        bottomPane.add(button17);
        final JButton button18 = new JButton();
        button18.setBackground(new Color(-1754827));
        button18.setBorderPainted(false);
        button18.setContentAreaFilled(false);
        button18.setMargin(new Insets(0, 0, 0, 0));
        button18.setMaximumSize(new Dimension(30,30));
        button18.setMinimumSize(new Dimension(30,30));
        button18.setOpaque(true);
        button18.setPreferredSize(new Dimension(30,30));
        button18.setText("1");
        bottomPane.add(button18);
        final JButton button19 = new JButton();
        button19.setBackground(new Color(-1754827));
        button19.setBorderPainted(false);
        button19.setContentAreaFilled(false);
        button19.setMargin(new Insets(0, 0, 0, 0));
        button19.setMaximumSize(new Dimension(30,30));
        button19.setMinimumSize(new Dimension(30,30));
        button19.setOpaque(true);
        button19.setPreferredSize(new Dimension(30,30));
        button19.setText("1");
        bottomPane.add(button19);
        final JButton button20 = new JButton();
        button20.setBackground(new Color(-141259));
        button20.setBorderPainted(false);
        button20.setContentAreaFilled(false);
        button20.setMargin(new Insets(0, 0, 0, 0));
        button20.setMaximumSize(new Dimension(30,30));
        button20.setMinimumSize(new Dimension(30,30));
        button20.setOpaque(true);
        button20.setPreferredSize(new Dimension(30,30));
        button20.setText("3");
        bottomPane.add(button20);
        final JButton button21 = new JButton();
        button21.setBackground(new Color(-291840));
        button21.setBorderPainted(false);
        button21.setContentAreaFilled(false);
        button21.setMargin(new Insets(0, 0, 0, 0));
        button21.setMaximumSize(new Dimension(30,30));
        button21.setMinimumSize(new Dimension(30,30));
        button21.setOpaque(true);
        button21.setPreferredSize(new Dimension(30,30));
        button21.setText("5");
        bottomPane.add(button21);
        final JButton button22 = new JButton();
        button22.setBackground(new Color(-1754827));
        button22.setBorderPainted(false);
        button22.setContentAreaFilled(false);
        button22.setMargin(new Insets(0, 0, 0, 0));
        button22.setMaximumSize(new Dimension(30,30));
        button22.setMinimumSize(new Dimension(30,30));
        button22.setOpaque(true);
        button22.setPreferredSize(new Dimension(30,30));
        button22.setText("1");
        bottomPane.add(button22);
        final JButton button23 = new JButton();
        button23.setBackground(new Color(-141259));
        button23.setBorderPainted(false);
        button23.setContentAreaFilled(false);
        button23.setMargin(new Insets(0, 0, 0, 0));
        button23.setMaximumSize(new Dimension(30,30));
        button23.setMinimumSize(new Dimension(30,30));
        button23.setOpaque(true);
        button23.setPreferredSize(new Dimension(30,30));
        button23.setText("3");
        bottomPane.add(button23);
        final JButton button24 = new JButton();
        button24.setBackground(new Color(-1754827));
        button24.setBorderPainted(false);
        button24.setContentAreaFilled(false);

        button24.setMargin(new Insets(0, 0, 0, 0));
        button24.setMaximumSize(new Dimension(30,30));
        button24.setMinimumSize(new Dimension(30,30));
        button24.setOpaque(true);
        button24.setPreferredSize(new Dimension(30,30));
        button24.setText("1");
        bottomPane.add(button24);
        final JButton button25 = new JButton();
        button25.setBackground(new Color(-141259));
        button25.setBorderPainted(false);
        button25.setContentAreaFilled(false);
        button25.setMargin(new Insets(0, 0, 0, 0));
        button25.setMaximumSize(new Dimension(30,30));
        button25.setMinimumSize(new Dimension(30,30));
        button25.setOpaque(true);
        button25.setPreferredSize(new Dimension(30,30));
        button25.setText("3");
        bottomPane.add(button25);
        final JButton button26 = new JButton();
        button26.setBackground(new Color(-12345273));
        button26.setBorderPainted(false);
        button26.setContentAreaFilled(false);
        button26.setMargin(new Insets(0, 0, 0, 0));
        button26.setMaximumSize(new Dimension(30,30));
        button26.setMinimumSize(new Dimension(30,30));
        button26.setOpaque(true);
        button26.setPreferredSize(new Dimension(30,30));
        button26.setText("4");
        bottomPane.add(button26);
        final JButton button27 = new JButton();
        button27.setBackground(new Color(-1754827));
        button27.setBorderPainted(false);
        button27.setContentAreaFilled(false);
        button27.setMargin(new Insets(0, 0, 0, 0));
        button27.setMaximumSize(new Dimension(30,30));
        button27.setMinimumSize(new Dimension(30,30));
        button27.setOpaque(true);
        button27.setPreferredSize(new Dimension(30,30));
        button27.setText("1");
        bottomPane.add(button27);
        final JButton button28 = new JButton();
        button28.setBackground(new Color(-12345273));
        button28.setBorderPainted(false);
        button28.setContentAreaFilled(false);
        button28.setMargin(new Insets(0, 0, 0, 0));
        button28.setMaximumSize(new Dimension(30,30));
        button28.setMinimumSize(new Dimension(30,30));
        button28.setOpaque(true);
        button28.setPreferredSize(new Dimension(30,30));
        button28.setText("4");
        bottomPane.add(button28);
        final JButton button29 = new JButton();
        button29.setBackground(new Color(-1754827));
        button29.setBorderPainted(false);
        button29.setContentAreaFilled(false);
        button29.setMargin(new Insets(0, 0, 0, 0));
        button29.setMaximumSize(new Dimension(30,30));
        button29.setMinimumSize(new Dimension(30,30));
        button29.setOpaque(true);
        button29.setPreferredSize(new Dimension(30,30));
        button29.setText("1");
        bottomPane.add(button29);
        final JButton button30 = new JButton();
        button30.setBackground(new Color(-141259));
        button30.setBorderPainted(false);
        button30.setContentAreaFilled(false);
        button30.setMargin(new Insets(0, 0, 0, 0));
        button30.setMaximumSize(new Dimension(30,30));
        button30.setMinimumSize(new Dimension(30,30));
        button30.setOpaque(true);
        button30.setPreferredSize(new Dimension(30,30));
        button30.setText("3");
        bottomPane.add(button30);
        final JButton button31 = new JButton();
        button31.setBackground(new Color(-291840));
        button31.setBorderPainted(false);
        button31.setContentAreaFilled(false);
        button31.setMargin(new Insets(0, 0, 0, 0));
        button31.setMaximumSize(new Dimension(30,30));
        button31.setMinimumSize(new Dimension(30,30));
        button31.setOpaque(true);
        button31.setPreferredSize(new Dimension(30,30));
        button31.setText("5");
        bottomPane.add(button31);
        final JButton button32 = new JButton();
        button32.setBackground(new Color(-12345273));
        button32.setBorderPainted(false);
        button32.setContentAreaFilled(false);
        button32.setMargin(new Insets(0, 0, 0, 0));
        button32.setMaximumSize(new Dimension(30,30));
        button32.setMinimumSize(new Dimension(30,30));
        button32.setOpaque(true);
        button32.setPreferredSize(new Dimension(30,30));
        button32.setText("4");
        bottomPane.add(button32);
        final JButton button33 = new JButton();
        button33.setBackground(new Color(-1754827));
        button33.setBorderPainted(false);
        button33.setContentAreaFilled(false);
        button33.setMargin(new Insets(0, 0, 0, 0));
        button33.setMaximumSize(new Dimension(30,30));
        button33.setMinimumSize(new Dimension(30,30));
        button33.setOpaque(true);
        button33.setPreferredSize(new Dimension(30,30));
        button33.setText("1");
        bottomPane.add(button33);
        final JButton button34 = new JButton();
        button34.setBackground(new Color(-1754827));
        button34.setBorderPainted(false);
        button34.setContentAreaFilled(false);
        button34.setMargin(new Insets(0, 0, 0, 0));
        button34.setMaximumSize(new Dimension(30,30));
        button34.setMinimumSize(new Dimension(30,30));
        button34.setOpaque(true);
        button34.setPreferredSize(new Dimension(30,30));
        button34.setText("1");
        bottomPane.add(button34);
        final JButton button35 = new JButton();
        button35.setBackground(new Color(-14776091));
        button35.setBorderPainted(false);
        button35.setContentAreaFilled(false);
        button35.setMargin(new Insets(0, 0, 0, 0));
        button35.setMaximumSize(new Dimension(30,30));
        button35.setMinimumSize(new Dimension(30,30));
        button35.setOpaque(true);
        button35.setPreferredSize(new Dimension(30,30));
        button35.setText("2");
        bottomPane.add(button35);
        final JButton button36 = new JButton();
        button36.setBackground(new Color(-14776091));
        button36.setBorderPainted(false);
        button36.setContentAreaFilled(false);
        button36.setMargin(new Insets(0, 0, 0, 0));
        button36.setMaximumSize(new Dimension(30, 30));
        button36.setMinimumSize(new Dimension(30, 30));
        button36.setOpaque(true);
        button36.setPreferredSize(new Dimension(30, 30));
        button36.setText("2");
        bottomPane.add(button36);
    }
}
